### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PriyanshuQ** [owerdogan/whoami-project#38]
![err1](https://user-images.githubusercontent.com/80645068/211211373-4bcde5de-fa64-483c-a1a5-ed05e64d7653.PNG)
![err2](https://user-images.githubusercontent.com/80645068/211211378-e9ecd2ef-a70a-4101-836c-c1cbb13fe48d.PNG)

**Comment by owerdogan** [comment]
i got you dude don't worry the patch will be released in 2-3 days. then just update your whoami client.

**Comment by owerdogan** [comment]
can you copy your /usr/share/kali-whoami/assests/sources/config file here: https://controlc.com
thanks!

**Comment by owerdogan** [comment]
I am still waiting for your answer.

**Comment by owerdogan** [comment]
fixed

**Comment by owerdogan** [comment]
Bug fixed and update released.

**Comment by u1tr0nex** [comment]
> Bug fixed and update released.
Is it fixed? I am still having the same error after changing localhost name.

**Comment by whatiscybersecurity** [comment]
I am getting the same error. I tried running --stop, but didn't fix it. This happened after I input "1,2,3,4,5,6,7,8" on the menu where it asks to enable options. 

Also `rm -r /home/host/kali-whoami` + `git clone https://github.com/omer-dogan/kali-whoami && cd kali-whoami && sudo make reinstall` and no luck

**Comment by owerdogan** [comment]
> Is it fixed? I am still having the same error after changing localhost name.

Sorry for the delay. I just released a new update again and now you can't get any error about the source file.
